services:
  media-downloader:
    build: .
    container_name: media-downloader
    restart: unless-stopped
    ports:
      - "30120:8080"
    volumes:
      - /mnt/Hem-NAS/media/UWTD-Nedladdningar:/downloads
